### ISSUE TITLE
很高兴能找到完成度较高的Nimsdk,但是我没能成功运行

### ISSUE THREAD

**Issue by sayatokido** [ZJQian/flutter_nimsdk#1]
![image](https://user-images.githubusercontent.com/34386267/71098178-41e8dd80-21ec-11ea-8f87-40d9747a61db.png)

**Comment by ZJQian** [comment]
import正常吗

**Comment by sayatokido** [comment]
是直接clone的example，然后初始化时就出现这个情况，flutter版本1.12.13

**Comment by sayatokido** [comment]
很抱歉，没有看到您写的“暂时只有ios版本“，我是用的android手机运行的

**Comment by ZJQian** [comment]
> 很抱歉，没有看到您写的“暂时只有ios版本“，我是用的android手机运行的

不好意思啊   这个插件暂时还不能双端使用，这个只是为我们自己的iOS项目封装的。Android端暂时还没开发。
